name: Build APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git zip unzip openjdk-11-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake
          pip install buildozer cython==0.29.19
      - name: Run Buildozer
        run: |
          buildozer init
          echo "requirements = python3, pillow, tqdm, kivy" >> buildozer.spec
          echo "android.permissions = INTERNET" >> buildozer.spec
          buildozer -v android debug
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: SpriteTools-APK
          path: bin/*.apk
